runs:
  using: "composite"
  steps:
    - run: echo action.yml; echo "$0"; env; pwd -P
      shell: bash
      env:
        action_path: ${{ github.action_path }}
        # https://github.com/rafaelgieschke/test/issues/2
