on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      url:
        type: string

permissions:
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.name || vars.name }}
      url: ${{ inputs.url }}
    env:
      name: ${{ inputs.name || vars.name }}
    steps:
      - run: |
          date -Is
